# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run Snyk security scan
        uses: snyk/actions/test@v3
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

